#!/bin/bash
apt update -y && apt upgrade -y
timedatectl set-timezone Asia/Jakarta
apt install -y nginx
apt install -y git
apt install -y php-cli php-xml php-curl php-zip php-mbstring php-dom php8.1-mysql php8.1-fpm php-bcmath
apt install -y mariadb-server
curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
apt install -y nodejs
systemctl start nginx
service php8.1-fpm start
